### ISSUE TITLE
Todo

### ISSUE THREAD

**Issue by fallcat** [featurecat/omega#1]
- [x] A1. create an update based interface like lizzie. 
- [x] A1A. must have Board.java from lizzie 
- [x] A1B. can read in sequences of moves by both mouse click and sgf move sequence. doesn't need to handle variations at all. 
- [x] A1C. supports button framework 

- [x] B1. Need a sgf parser. it literally can be the simplest thing, because foxy is simple, but might be better to use the open-source one. it's more complete. 
- [ ] B2. need a way of marking off areas for the search. 
- [x] B3. need a way of inputting alternating, black, or white stones. 
- [x] B4. Need a way to detect if the search is a match or not. 
- [x] B5. Need a way to get Leelaz output about the position. 
- [x] B6. need a way to store Leelaz output for later 
- [x] B7. need to be able to specify folder of go games. 
- [x] B8. Need a way to display a heat map 
B8’. Display a heat map is a specific region 
- [x] B9. Remove stone 

- [ ] C1. need to run a serial search of all go positions. parallel can be later. and store the Leela zero outputs. 
- [ ] C2. need to be able to display the results of search. hopefully in real time! 

- [ ] D1. parallelize search??
